version: '3'
services:
  app:
    container_name: nodeapp_golli
    build: .
    command: nodemon --watch . -e js index.js
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www/
    links:
      - "mongo:mongohost"

  mongo:
    container_name: mongo_golli
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  

  vue:
      container_name: vueapp_golli
      build: ./app/vue_app
      command: 'npm run serve'
      ports:
        - "8080:8080"
      volumes:
        - ./app/vue_app:/var/www/vue
      working_dir: /var/www/vue

